apiVersion: v1
kind: Namespace
metadata:
  name: ${SC2_NAMESPACE}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-py
  namespace: ${SC2_NAMESPACE}
spec:
  template:
    metadata:
      annotations:
      labels:
        apps.sc2.io/name: helloworld-py
    spec:
      runtimeClassName: ${RUNTIME_CLASS_NAME}
      securityContext:
        runAsUser: 1000
      containers:
        - image: ${CTR_REGISTRY_URL}/helloworld-py:unencrypted
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
